### ISSUE TITLE
Retrieving avatar fails when using WP_Post

### ISSUE THREAD

**Issue by blobaugh** [10up/simple-local-avatars#20]
When calling `get_avatar()` and passing in a `WP_Post` object Simple Local Avatars fails to properly pick up the user id. This is because the core `get_avatar()` supports more methods of finding the user id than the plugin's `get_avatar()`.

Example code (where $post is the global on a single view):
```$avatar = get_avatar( $post, '72' )```

You can see all the types supported by core at
https://github.com/WordPress/WordPress/blob/master/wp-includes/link-template.php#L4091
* Number
* String
* WP_User
* WP_Post
* WP_Comment

Support in the plugins is at
https://github.com/10up/simple-local-avatars/blob/develop/simple-local-avatars.php#L66
* Number
* String
* Generic object with post_id property

**Comment by jeffpaul** [comment]
@blobaugh thanks for the feedback, it's much appreciated!  I'm tentatively adding this to our 2.2 milestone, but note we don't have a timeline on that yet as its unplanned.  If you're able to work on a Pull Request, that would be welcomed.  Otherwise, we'll look into reviewing this and any possible resolution.

**Comment by oscarssanchez** [comment]
Hey @blobaugh ,

I made PR #47 for this, can you test this works for you ?
