### ISSUE TITLE
Ensure avatars work correctly on a network install

### ISSUE THREAD

**Issue by adamsilverstein** [10up/simple-local-avatars#26]
#### Description
I would expect that the plugin would work on a network install.

#### Actual results
On a network install, after setting an avatar for my user, WordPress continued to use my gravatar instead.

**Comment by helen** [comment]
Just so we can be sure to cover all scenarios - was the plugin network activated? Which site were you on?

**Comment by adamsilverstein** [comment]
Hmm, I thought this was on a single site but having trouble reproducing this at all that way...

What I do see that might be a bug is this:

* network activate plugin
* edit your user profile on network (my sites -> network admin -> users) set an avatar
* switch to different sites, the avatar change only works on the root site, i would expect the custom avatar to work across the network, is that right?
* my testing may be off because i've activated/deactivate both ways many times, would be good to test on a fresh install.

**Comment by dinhtungdu** [comment]
We got a new report on w.org
> when a user uploads/updates a local avatar to one of our subdirectory-based sites via your plugin (v2.1.1/latest), it appears to delete their local avatar uploaded to another of our subdirectory-based sites.

See the original report: https://wordpress.org/support/topic/multisite-issue-45/

@helen @jeffpaul Which should be the correct behavior for this case. Should the local avatar be subsite only or network-wide?

**Comment by jeffpaul** [comment]
My preference is that users would have to upload an avatar to each network site and not that uploading to one network site would make it the avatar for other network sites for the same user.  I can see that for some people who want to use the same avatar across sites that this would be mildly inconvenient for them to have to upload the same avatar for each network site.  However, the case I'd like to avoid is a user not realizing the sites were part of the same network, wanting different avatars on each site, and having the suboptimal user experience of an avatar from a different network site being set for them on a separate network site which they would not have otherwise chosen to use the avatar on.

All that said, I'm going to move this out of the current milestone and we can look to tackle this once we have better details on how we expect things to work on a network install in an upcoming release.

**Comment by Soean** [comment]
We have just noticed the problem ourselves. When an avatar is saved, the media ID is used. But this media ID is not available in other sites in the multisite network. Maybe in multisite we add the site id to the meta_key? Like `simple_local_avatar_SITEID`

**Comment by jeffpaul** [comment]
@helen @dkotter @dinhtungdu any thoughts on @Soean's note above as a possible option for how to resolve this issue?

**Comment by dinhtungdu** [comment]
Yeah, it's possible to solve the issue using Soean's approach. And I agree that users need to upload an avatar for each site they have access to, this prevents potential confusion if we use one avatar for all sites.

**Comment by jeffpaul** [comment]
@Soean would you want to work on a PR that resolves this as you suggested?

**Comment by helen** [comment]
I don't think this plugin has had any deliberate thought put into multisite workings :) I think we probably need to consider expanded functionality in order for this to feel like it works "correctly". My initial thoughts are to have this kind of mirror the way Restricted Site Access handles things - network-level settings if network activated, where you can decide if the settings should be enforced across the network (i.e. same avatar used for all sites) or can be set per-site (i.e. separate avatar per site). It would probably need to default to the former, both because of the way it currently works and because it's truthfully more "correct" given the way user profiles work on networks.

Open to other / more detailed thoughts.

**Comment by dkotter** [comment]
I've put together a PR (#72) to take a stab at addressing this. That PR adds new network settings and those settings can either be used as the default or enforced across all sites (similar to Restricted Site Access). There's also a new setting to choose whether avatars are shared or unique across sites (default right now is shared). Let me know if anyone has thoughts on this approach. Thanks!

**Comment by scheinercc** [comment]
I was wondering if there is an internal release date yet for version 2.3.0 as PR 72 has been marked for that release?

**Comment by jeffpaul** [comment]
@scheinercc no immediate timeline, though in looking at #72 it looks like its in need up a slight update before it would be ready to merge.  Suffice to say it doesn't look like a near term timeline, but if that's of a particularly urgent or important need for you let me know.

**Comment by scheinercc** [comment]
Thanks for the quick reply Jeff. It is a blocker for me at the moment. I am using the author avatars on three subsites and it took me a while to realise that they get deleted from one site when updating the other. I then got here right around the time when @dkotter and was waiting for the patch to land ;) Now the question is, if it is still worth waiting a little longer for it to land in a new release or to better find a more timely work around instead!?

**Comment by mas31550** [comment]
Hi I was wondering if there's any update to PR 72 being merged in to next release? This bug is a blocker for a particular project and this fix would be great!

**Comment by jeffpaul** [comment]
@mas31550 I'll look to review that with the team next week, no firm commitment on if that PR is ready but once it or any replacement one is I'd say we'd likely release once one is merged as it is a pretty important update for folks.  Stay tuned for updates here, thanks!

**Comment by henrywright** [comment]
If user profile information is shared network-wide, such as name and description, would it make sense to share the same user avatar network-wide?
