### ISSUE TITLE
Add simple shortcode to upload image avatar any page

### ISSUE THREAD

**Issue by campiotto** [10up/simple-local-avatars#60]
**Is your enhancement related to a problem? Please describe.**

There is only one plugin in the wordpress repository that makes a shortcode available for uploading the avatar and does it in a very polluted way. It would be great to have this implemented in your plugin which is minimalist.

**Describe the solution you'd like**

An elegant solution, with no filament and pollution, the user just places the shortcode [upload_avatar msg = "upload my avatar"] wherever he wants, and an upload my avatar button appears, clicking on it, opens a pop-up to upload the image and to save.

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeffpaul** [comment]
@campiotto can you share some more details on the type of page that you'd expect this functionality to appear on and the broader user story that this request is part of?  I'd like to ensure we understand the larger issue you're trying to solve so we take that into consideration... thanks!

**Comment by campiotto** [comment]
Hi Jeff, let's go! 

I will tell you my real scenario and you will see that there is a very needy audience needing `feature in your plugin.

Today there are many websites that use page builders, they are a little limited when referring to the "my account" page, it is basically impossible through a page builder for a user to get a field to change their profile picture to use in the website comments or on a member page for example.

Even if you're using a plugin like Advanced Custom Fields, you'll have a lot of work until this works.

The only way to have this working today is through a member system that already includes this or through a plugin that customizes the entire my account page.

There is no freedom for the designer to make the page as he would like and to place the option to update the profile photo in the place he would like.

What I imagined was a shortcode, which shows the person's photo, if they place the mouse on top a favicon of a camera appears, if they click, it opens a popup to send the photo, confirm and that's it.

**Comment by jeffpaul** [comment]
@campiotto ok, I see what you're trying to achieve.  May also be something to consider here as a block in the block editor as once Full Site Editing is fully launched being able to place a block like this would also cover a similar functionality as a shortcode.

**Comment by campiotto** [comment]
I believe that if this works as a block editor widget, it will not work on other editors, I still think that the most minimalist way is a shortcode because with a class configured for it, it is possible to adapt it to any editors.

**Comment by campiotto** [comment]
Hi Jeff, how are you? Was this feature added?

**Comment by jeffpaul** [comment]
@campiotto no, but if you want to work on a PR then we can review and look to get that into a future release.

**Comment by campiotto** [comment]
I don't know how to develop this.

**Comment by wolvyreen** [comment]
This shortcode was the ONLY reason I ditched Simple Local Avatar for Basic User Avatars.  Basic User Avatars has a shortcode but is fairly limited.  It works perfectly for when you have customised profile update pages that you want the end user to upload a profile picture but not have access to the WordPress dashboard.

We run a membership site and they need to upload their own profile pics WITHOUT having access to the Wordpress dashboard.  Basic User Avatars allows us to use a shortcode which allows us to restrict the Wordpress dashboard from the end users.  Without the shortcode, this is not possible.

**Comment by jeffpaul** [comment]
@wolvyreen is this something you'd want to work on a PR to add to Simple Local Avatars?

**Comment by planetahuevo** [comment]
Considering that https://github.com/strangerstudios/basic-user-avatars/ is a fork of this one, the code should be there somewhere.
I am not a developer so no idea where to start. 
But I agree this will be a great addition to the plugin.

**Comment by wolvyreen** [comment]
> @wolvyreen is this something you'd want to work on a PR to add to Simple Local Avatars?

Same seat as planethuevo. Not a developer but as he mentioned the shortcode code should be in the basic user avatars plugin that you could maybe ask stranger studios if you could credit them?

What I would also like to see is a file size limitation on the plugin because otherwise people can upload MASSIVE pictures and effect your page loads

**Comment by helen** [comment]
Hello! Just to make sure I'm understanding the request, it's for there to be some kind of front end upload functionality bundled with the plugin? Specifically to the technical side of the request, I would decline to develop new shortcodes for a number of reasons.

While I empathize with what you're trying to accomplish, I'm currently of the mind that this is outside the scope of this plugin. **Simple** Local Avatar's goal is to augment core functionality, not create its own. This isn't a matter of competing with other plugins - if another one serves your goals better, then I am happy that the WordPress ecosystem has done its job! If nothing exists as a free public plugin, then there is some combination of demand and difficulty in implementation that would also apply to our own team. There are many moving parts involved in creating something that's usable on the front end of a wide variety of themes that we just do not have the bandwidth to manage, and I am loathe to have my team work on a new feature involving shortcodes, it's just not the right move for future maintenance and usability.

**Comment by jeffpaul** [comment]
@campiotto after talking through this internally our recommendation would be to utilize a separate plugin that, like Simple Local Avatars does, hooks into the core avatar function and provides a shortcode for your use.  This otherwise is not likely something that we'll look to add to Simple Local Avatars as its outside the core focus that we have for our plugin:
> Adds an avatar upload field to user profiles. Generates requested sizes on demand, just like Gravatar! Simple and lightweight.

Thank you for sharing your feedback on the plugin and we welcome future comments and feedback, but for now I'm going to close out this enhancement request.

**Comment by planetahuevo** [comment]
"Simple Local Avatar's goal is to augment core functionality, not create its own. "
I am not sure how can you "augment"  without creating new stuff... 
But I understand you are not interested on this particular functionality (for the reasons outlined, difficulty and scope, which are valid reasons). No problem at all with that. :) 
Thanks for considering it.

**Comment by bluesteamhost** [comment]
I agree with @planetahuevo.

You can't augment something without adding to it.  The very definition of augmenting is to make (something) greater by adding to it.

Just Google "augment definition" and you will get the idea.

You also made it sound like it's so much work to implement and yet, Stranger Studios did it simply and effectively without issues in the fork **Basic User Avatars**.

Anyways....

So, in saying that though, I respectfully disagree about your sentiments because in my opinion you're not creating new functionality but rather **simply** extending the current functionality and the plugins "reach" to allow for the existing plugin to be accessed from anywhere on the site and not only through the wordpress admin dashboard. This would not be **NEW** functionality. It's simply extending its accessibility of it from anywhere on the site. So in my opinion that is not **CORE** functionality.

But hey, it's your plugin. We aren't here to tell you what to do. Only give you feedback and indicate _(in our opinion)_ where your plugin is falling short and if you disagree with us... well then.... there it is... we will simply use a plugin from another developer who _(in our opinion)_ can see the potential value in the growth of its user base by implementing a simple shortcode that enables their users to access the plugin from anywhere on Wordpress and not just in one place.

I have to say it... what a shame! :(   Good luck with your plugin.
